# Generated by Django 2.2.11 on 2020-03-30 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0002_add_synclist_20200330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='synclist',
            name='policy',
            field=models.CharField(choices=[('blacklist', 'blacklist'), ('whitelist', 'whitelist')], default='blacklist', max_length=64),
        ),
    ]
