---
version: 1
disable_existing_loggers: false
dynaconf_merge: true
filters:
  require_debug_true:
    (): django.utils.log.RequireDebugTrue
formatters:
  simple:
    format: "{levelname} {message}"
    style: "{"
  verbose:
    format:
      "{levelname} {asctime} {name} {module}:{funcName}:{lineno:d} {process:d}
      {thread:d} {message}"
    style: "{"
handlers:
  console:
    class: logging.StreamHandler
    formatter: verbose
    level: DEBUG
    # filters:
    #  - require_debug_true
  collection_import:
    class: pulp_ansible.app.logutils.CollectionImportHandler
    level: DEBUG
    formatter: simple
loggers:
  "":
    handlers:
      - console
    level: DEBUG
  django:
    propagate: true
  django.server: {}
    # propagate: true
  django.db:
    level: INFO
  django.request: {}
  django.utils.autoreload:
    level: ERROR
  dynaconf:
    level: INFO
  galaxy_ng: {}
  galaxy_ng.auth: {}
  galaxy_pulp: {}
  pulpcore: {}
  pulpcore.content:
    level: INFO
  pulpcore.tasking.services.worker_watcher:
    level: INFO
  pulp_ansible: {}
  pulp_ansible.app.tasks.collection.import_collection:
    level: INFO
    handlers:
      - collection_import
    propagate: false
  requests: {}
  urllib3: {}
  MARKDOWN:
    level: INFO
